language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
install:
    - make install
before_script:
    - phpenv rehash
script: make test_phpunit
env:
    global:
        - COMPOSER_PREFER_SOURCE=--prefer-source
notifications:
    irc: 'irc.freenode.org#thefox'
    on_success: never
    on_failure: always